Event/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("eventm.urls"))
]

eventm/urls.py
from django.urls import path
from .views import  approved_events, rejected_events, approve_event, reject_event, buy_tickets
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    path("contact", views.contact, name="contact"),
    path("logina_view", views.logina_view, name="logina_view"),
    path("dash_analytics", views.dash_analytics, name="dash_analytics"),
    path("logouta_view", views.logouta_view, name="logouta_view"),
    path("loginu_view", views.loginu_view, name="loginu_view"),
    path("signup_view", views.signup_view, name="signup_view"),
    path("dash_contact", views.dash_contact, name="dash_contact"),
    path("user_dashboard", views.user_dashboard, name="user_dashboard"),
    path('all_events', views.all_events, name='all_events'),
    path('approved_events/', approved_events, name='approved_events'),
    path('rejected_events/', rejected_events, name='rejected_events'),
    path('approve_event/<int:event_id>/', approve_event, name='approve_event'),
    path('reject_event/<int:event_id>/', reject_event, name='reject_event'),
    path('buy-tickets/<int:event_id>/', buy_tickets, name='buy_tickets'),

]

eventm/models.py
# models.py
from django.contrib.auth.models import User
from django.db import models

class ContactFormEntry(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name
    
class Event(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    location = models.CharField(max_length=255)
    event_type = models.CharField(max_length=255)
    status = models.CharField(max_length=20, default='pending')  # Default status is 'pending'
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.id}: {self.name}: {self.status}"

class UserEventRegistration(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    status = models.CharField(max_length=255, default='pending')  # Status can be 'pending', 'approved', 'rejected', etc.

    def __str__(self):
        return f"{self.user.username} - {self.event.name} ({self.status})"
    
class Ticket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey('Event', on_delete=models.CASCADE)
    tickets_purchased = models.PositiveIntegerField(default=0)
    purchase_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.event.name}"

eventm/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import ContactFormEntry, Event, Ticket
class LoginaForm(forms.Form):
    username = forms.CharField(label='Username', max_length=150)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)


class SignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1']

class LoginuForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactFormEntry
        fields = ['name', 'email', 'message']
class EventForm(forms.ModelForm):
    EVENT_TYPE_CHOICES = [
        ('conference', 'Conference'),
        ('workshop', 'Workshop'),
        ('concert', 'Concert'),
        ('wedding', 'Wedding')
        # Add more choices as needed
    ]

    event_type = forms.ChoiceField(choices=EVENT_TYPE_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Event
        fields = ['name', 'description', 'location', 'event_type']
        
class TicketPurchaseForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['tickets_purchased']
        
        

eventm/views.py
from django.contrib.sessions.models import Session
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import JsonResponse
from django.http import HttpResponse
import base64, time
from .forms import LoginaForm, SignupForm, LoginuForm, ContactForm, EventForm, TicketPurchaseForm
from .models import ContactFormEntry, Event, UserEventRegistration
import face_recognition, os
import matplotlib
matplotlib.use('Agg')  # Use Agg backend (non-interactive) for Matplotlib
import matplotlib.pyplot as plt
from io import BytesIO

def check_facial_recognition(image_file):
    unknown_image = face_recognition.load_image_file(image_file)
    unknown_encoding = face_recognition.face_encodings(unknown_image)[0]
    for i in os.listdir(r'images/admin'):
        image_path=os.path.join(r'images/admin',i)
        known_image = face_recognition.load_image_file(image_path)    
        known_encoding = face_recognition.face_encodings(known_image)[0]
        results = face_recognition.compare_faces([known_encoding], unknown_encoding)
        print(results)
        if results[0]:
            print(i)
            return True    
    
    return False

def convert_base64_to_image(base64_data):
    if base64_data is None:
         print("Error: Image data not found in the request.")
         return HttpResponse("Image data not found in the request.", status=400)

    # Remove the data URL prefix if it exists
    base64_data = base64_data.replace("data:image/png;base64,", "")

    if not base64_data:
        print("Error: Empty base64 data received.")
        return None

    try:
        # Decode the base64 string to bytes
        image_data = base64.b64decode(base64_data)
        # Set the path where you want to save the image
        path = "C:\\Users\\Hammad Yasin\\Event\\images\\"
        # Create a unique file name based on the current time
        file_name = str(time.time()) + ".png"
        # Write the image data to the file
        with open(os.path.join(path, file_name), "wb") as f:
            f.write(image_data)
        # Return the file name
        return file_name
    except Exception as e:
        print(f"Error during base64 decoding: {e}")
        return None

def index(request):
    return render(request, "eventm/index.html")

def add(request):
    success_message = None

    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            # Associate the currently logged-in user with the event
            form.instance.user = request.user

            # Save the form data to the database
            event = form.save()
            UserEventRegistration.objects.create(user=request.user, event=event, status='pending')
            success_message = 'Event Request Successfully submitted!'
            form = EventForm()  # Reset the form for a new submission
        else:
            messages.error(request, 'There was an error with your submission. Please check the form and try again.')
    else:
        form = EventForm()

    return render(request, "eventm/addevent.html", {'form': form, 'success_message': success_message})

def contact(request):
    success_message = None

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Save the form data to the database
            form.save()
            success_message = 'Thank you for your message! We will get back to you soon.'
            form = ContactForm()  # Reset the form for a new submission
        else:
            messages.error(request, 'There was an error with your submission. Please check the form and try again.')
    else:
        form = ContactForm()

    return render(request, "eventm/contact_us.html", {'form': form, 'success_message': success_message})


def logina_view(request):
    if request.method == 'POST':
        form = LoginaForm(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            # Get the base64 data from the form
            base64_data = request.POST.get('image')
            
            if base64_data is None:
                error_message = 'Image data not found in the request.'
                print("Error:", error_message)
                return JsonResponse({'success': False, 'error': error_message})

            path = "C:\\Users\\Hammad Yasin\\Event\\images\\"
            # Convert the base64 data to an image file and get the file name
            image_file = convert_base64_to_image(base64_data)
            image_path= os.path.join(path,image_file)
            if image_file is not None:
                if user is not None:
                    if check_facial_recognition(image_path):
                        login(request, user)
                        messages.success(request, 'Login successful.')
                        return redirect('dash_analytics')
                    else:
                        error_message = 'Facial recognition failed.'
                        print("Error:", error_message)
                        return JsonResponse({'success': False, 'error': error_message})
                else:
                    error_message = 'Invalid login credentials.'
                    print("Error:", error_message)
                    return JsonResponse({'success': False, 'error': error_message})
            else:
                error_message = 'Invalid image data.'
                print("Error:", error_message)
                return JsonResponse({'success': False, 'error': error_message})
    else:
        form = LoginaForm()

    return render(request, 'eventm/logina.html', {'form': form})

def dash_analytics(request):
    # Check if the user is authenticated
    if not request.user.is_authenticated:
        # Redirect to login if not authenticated
        return redirect('index')

    # Check if the session has expired
    if '_session_expiry' not in request.session:
        # Set the session expiry timestamp
        request.session['_session_expiry'] = int(time.mktime((timezone.now() + timezone.timedelta(minutes=15)).timetuple()))

    if int(request.session['_session_expiry']) < int(time.mktime(timezone.now().timetuple())):
        # Logout the user and redirect to the login page
        logout(request)
        messages.warning(request, 'Session expired. Please log in again.')
        return redirect('index')

    # Update the session expiry timestamp
    request.session['_session_expiry'] = int(time.mktime((timezone.now() + timezone.timedelta(minutes=15)).timetuple()))

    # Add the logic for generating charts
    category_labels = ['Conference', 'Workshop', 'Concerts', 'Weddings']
    category_counts = [30, 45, 20, 15]
    colors_categories = ['#333a55', '#4d5573', '#667190', '#7f8aae']

    # Create a bar chart for event categories
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.bar(category_labels, category_counts, color=colors_categories)
    ax.set_xlabel('Event Categories')
    ax.set_ylabel('Number of Events')
    ax.set_title('Event Category')

    # Save the category chart to a BytesIO object
    category_stream = BytesIO()
    plt.savefig(category_stream, format='png')
    plt.close()

    # Pie chart for event status
    status_labels = ['Completed', 'Approved', 'Ongoing']
    status_counts = [60, 25, 15]
    colors_status = ['#7CAEA3', '#A4D4BE', '#CCE8D8']

    # Create a pie chart for event status
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.pie(status_counts, labels=status_labels, autopct='%1.1f%%', colors=colors_status, startangle=90)
    ax.axis('equal')  # Equal aspect ratio ensures the pie chart is circular
    ax.set_title('Event Status')

    # Save the status chart to a BytesIO object
    status_stream = BytesIO()
    plt.savefig(status_stream, format='png')
    plt.close()

    # Encode both image streams to base64
    category_base64 = base64.b64encode(category_stream.getvalue()).decode('utf-8')
    status_base64 = base64.b64encode(status_stream.getvalue()).decode('utf-8')

    # Pass the base64 image data to the template
    context = {
        'category_base64': category_base64,
        'status_base64': status_base64,
    }

    return render(request, "eventm/dash_analytics.html", context)

def logouta_view(request):
    logout(request)
    return redirect('index')

def signup_view(request):
    if request.method == 'POST':
            username = request.POST.get('username')
            email = request.POST.get('email')
            password1 = request.POST.get('password1')
            user = User.objects.create_user(username, email, password1)
            messages.success(request, 'Sign up successful. You can now log in.')
            # Redirect to a success page or any other desired page
            return redirect('loginu_view')
    else:
        form = SignupForm()

    return render(request, 'eventm/signup.html', {'form': form})
def loginu_view(request):
    form = LoginuForm()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
                login(request, user)
                messages.success(request, 'Login successful.')
                return redirect('user_dashboard')  # Replace 'index' with your desired page
        else:
            # Invalid login credentials
            messages.error(request, 'Invalid login credentials.')
            
    # Render the login page
    return render(request, 'eventm/loginu.html',{'form': form}) 

eventm/templates/eventm/addevent.html
{% extends "eventm/layout1.html" %}
{% block body %}
<style>

    h1 {
        color: #333;
        text-align: center;
    }
    
    form {
        max-width: 600px;
        margin: 20px auto; 
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    
    label {
        display: block;
        margin-bottom: 8px;
        color: #333;
    }
    
    input,
    textarea, select {
        width: calc(100% - 16px); /* Adjusted width to account for padding */
        padding: 8px;
        margin-bottom: 16px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
    }
    
    button {
        background-color: #4caf50;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }
    
    button:hover {
        background-color: #45a049;
    }
    
    a {
        color: #333;
        text-decoration: none;
        display: block;
        margin-top: 16px;
    }
    
    a:hover {
        color: #4caf50;
    }

    </style>
  <h1>Fill in the details!</h1>
<form method="post" action="{% url 'add' %}">
    {% csrf_token %}
    {% if success_message %}
        <div class="alert alert-success" style="color: green; text-align: center;">
            {{ success_message }}
        </div>
    {% endif %}
    <label for="id_name">Name:</label>
    {{ form.name }}
    
    <label for="id_description">Description:</label>
    {{ form.description }}
    
    <label for="id_location">Location:</label>
    {{ form.location }}
    
    <label for="id_event_type">Event Type:</label>
    {{ form.event_type }}
    
    <button type="submit">Submit</button>
</form>

{% endblock %}

eventm/templates/eventm/approved_events.html
{% extends "eventm/dashboard.html" %}
{% block body %}
  {% if approved_events %}
    <h1>Approved Events</h1>
    {% for event in approved_events %}
      <div style="border: 1px solid #ccc; padding: 10px; margin-bottom: 20px;">
        <p style="font-size: 18px; font-weight: bold;">Name: {{ event.name }}</p>
        <p><strong>Description:</strong> {{ event.description }}</p>
        <p><strong>Location:</strong> {{ event.location }}</p>
      </div>
    {% endfor %}
  {% else %}
    <p>No approved events available.</p>
  {% endif %}
{% endblock %}

eventm/templates/eventm/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'css/base.css'%}">
    <title>Login</title>
</head>

<body>
    {% block body %}
    {% endblock %}

    <div id="videoContainer">
        <div>
            <h1 style="text-align: center;">Take Photo</h1>
            <video id="video" width="320" height="240"></video>
        </div>
        <div style="margin-left: 40px; margin-top: 20px;">
        <button type="button" id="startVideo"><i class="fas fa-video"></i> Start Video</button>
        <button type="button" id="captureImage"><i class="fas fa-camera"></i> Capture Image</button>
        </div>
        <div>
            <h1 style="text-align: center;">Captured Photo</h1>
            <canvas id="canvas" width="320" height="240"></canvas>
        </div>
    </div>
    <script>
        const video = document.getElementById('video');
        let isVideoPlaying = false;
        let mediaStream = null;

        document.getElementById('startVideo').addEventListener('click', () => {
            if (!isVideoPlaying) {
                navigator.mediaDevices.getUserMedia({ video: true })
                    .then((stream) => {
                        video.srcObject = stream;
                        video.play();
                        isVideoPlaying = true;
                        mediaStream = stream;
                    })
                    .catch((error) => {
                        console.error('Error accessing camera:', error);
                    });
            }
        });

        document.getElementById('startVideo').addEventListener('dblclick', () => {
            if (isVideoPlaying) {
                video.pause();
                isVideoPlaying = false;

                if (mediaStream) {
                    const tracks = mediaStream.getTracks();
                    tracks.forEach(track => track.stop());
                }
            }
        });

        document.getElementById('captureImage').addEventListener('click', () => {
            const canvas = document.getElementById('canvas');
            const context = canvas.getContext('2d');
            context.drawImage(video, 0, 0, canvas.width, canvas.height);

            const imageDataURL = canvas.toDataURL('image/png');
            document.getElementById('base64Image').value = imageDataURL;

            console.log('Captured Image Data:', imageDataURL);
        });

        document.getElementById('captureImageButton').addEventListener('click', () => {
            const canvas = document.getElementById('canvas');
            const context = canvas.getContext('2d');
            context.drawImage(video, 0, 0, canvas.width, canvas.height);

            const imageDataURL = canvas.toDataURL('image/png');
            document.getElementById('base64Image').value = imageDataURL;

            console.log('Captured Image Data:', imageDataURL);
        });

        function validateForm() {
            const base64Image = document.getElementById('base64Image').value;

            if (!base64Image) {
                const errorDiv = document.getElementById('imageError');
                errorDiv.innerHTML = 'Please capture an image.';
                return false;
            }

            return true;
        }
    </script>
</body>
</html>

eventm/templates/eventm/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'css/base.css'%}">
    <title>Login</title>
</head>

<body>
    {% block body %}
    {% endblock %}

</body>
</html>

eventm/templates/eventm/buy_tickets.html
{% extends 'eventm/user_dash.html' %}

{% block body %}
  <div class="page-container">
    <div class="event-details-container">
      <h2>Buy Tickets for {{ event.type }}</h2>
      <p>{{ event.description }}</p>
      <form method="post" action="{% url 'buy_tickets' event_id=event.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">Purchase Tickets</button>
      </form>
      <a href="{% url 'user_dashboard' %}">Back to Dashboard</a>
    </div>
  </div>

<style>
  body {
    margin: 0;
    padding: 0;
    height: 100%;
  }

  .page-container {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
  }

  .event-details-container {
    flex-grow: 1;
    padding: 20px;
    max-width: 800px;
    margin: 0 auto;
    box-sizing: border-box;
  }

  a {
    display: block;
    margin-top: 10px;
    text-decoration: none;
    color: #3498db;
  }

  /* Sticky Footer */
  .footer {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 10px;
  }
</style>

{% endblock %}

eventm/templates/eventm/contact_us.html
{% extends "eventm/layout.html" %}
{% block body %}
<style>
    h1 {
        color: #333;
        text-align: center;
    }

    .contact-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        min-height: 70vh;
    }

    form {
        max-width: 800px;
        margin: 20px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .column {
        flex-basis: calc(48% - 8px);
        box-sizing: border-box;
    }

    input,
    textarea {
        width: 100%;
        padding: 8px;
        margin-bottom: 16px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    .message-textarea {
        flex-basis: 100%;
        height: 150px; /* Adjust the height as needed */
    }

    button {
        background-color: #4caf50;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        display: block;
        margin: auto; /* Center the button */
    }

    button:hover {
        background-color: #45a049;
    }

    a {
        color: #333;
        text-decoration: none;
        display: block;
        margin-top: 16px;
    }

    a:hover {
        color: #4caf50;
    }
</style>

<div class="contact-container">
    <h1>Contact Us</h1>
    {% if success_message %}
        <div class="alert alert-success">
            {{ success_message }}
        </div>
    {% endif %}
    <form method="post" action="">
        {% csrf_token %}
        <div class="column">
            <label for="name">Your Name:</label>
            <input type="text" name="name" required>

            <label for="email">Your Email:</label>
            <input type="email" name="email" required>
        </div>

        <div class="column">
            <label for="message">Your Message:</label>
            <textarea name="message" required></textarea>
            <button type="submit">Submit</button>
        </div>
    </form>
</div>

{% endblock %}

eventm/templates/eventm/dash_contact.html
{% extends "eventm/dashboard.html" %}
{% block body %}
<table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Message</th>
        <th>Action</th>  <!-- New column for the "Reply" button -->
      </tr>
    </thead>
    <tbody>
      {% for entry in contact_entries %}
        <tr>
          <td>{{ entry.name }}</td>
          <td>{{ entry.email }}</td>
          <td>{{ entry.message }}</td>
          <td>
            <!-- Add a "Reply" button with a link to a reply view -->
            <a href="#" class="reply-button">Reply</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

eventm/templates/eventm/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Dashboard</title>
  <style>
    body {
      font-family: Roboto, -apple-system, 'Helvetica Neue', 'Segoe UI', Arial, sans-serif;
      margin: 0;
      padding: 0;
    }

    .sidebar {
      padding-top: 80px;
      height: 100%;
      width: 260px;
      position: fixed;
      z-index: 1;
      top: 0;
      left: 0;
      background-color: #333a55;
      overflow-x: hidden;
    }

    .sidebar a {
      text-align: center;
      padding: 30px;
      text-decoration: none;
      font-size: 20px;
      color: #fff;
      display: block;
    }

    .sidebar a:hover {
      color: #ffffff;
      background-color: #818181;
    }

    /* Style the page content */
    .page-content {
      margin-left: 260px;
      transition: margin-left 0.5s;
      padding: 16px;
    }

    .header {
      position: fixed;
      top: 0;
      right: 0;
      height: 80px;
      width: calc(100% - 260px);
      background-color: #333a55;
      z-index: 2;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .header h1 {
      padding-left: 30%;
      color: #fff;
    }

    .header_button {
      background-color: #333;
      border: none;
      height: 80px;
      width: 150px;
      font-size: 20px;
      cursor: pointer;
      text-align: center;
      position: absolute;
      top: 50%;
      right: 0;
      transform: translateY(-50%);
      display: flex;
      justify-content: center;
      align-items: center;
      /* Center the text vertically */
      color: white;
      /* Set text color */
    }

    .header_button:hover {
      background-color: gray;
      color: #f1f1f1;
      transition: 0.3s;
    }

    .header a {
      text-decoration: none;
      color: white;
    }

    /* New styles for chart containers */
    .total-events-container,
    .total-attendees-container {
      padding-left: 25%;
      padding-top: 5%;
      text-align: center;
      margin: 10px;
      /* Reduce margin */
      width: 45%;
      /* Adjust the width of each container */
      display: flex;
      /* Display containers in a line */
      justify-content: space-between;
      /* Align containers with space between them */
    }

    .total-events-container h3,
    .total-attendees-container h3 {
      color: #333;
    }

    .total-events-container p,
    .total-attendees-container p {
      font-size: 24px;
      font-weight: bold;
      margin: 10px 0;
      color: #333;
      border: 1px solid #3498db;
      /* Add different border color */
      border-radius: 10px;
      /* Add border radius */
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      /* Add box shadow */
      width: 100%;
      /* Adjust the width of each container */
    }

    .charts-container {
      display: flex;
      justify-content: space-between;
      padding-top: 20px;
      /* Reduce margin */
    }

    .chart-container {
      flex: 0 0 48%;
      /* Adjust the width as needed */
      text-align: center;
      margin: 0 5px;
      border: 1px solid #fff;
      /* Add border */
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      /* Add box shadow */
    }

    .chart-container img {
      width: 100%;
      height: 300px;
    }

    .chart-container p {
      margin: 10px 0 0;
      color: #333;
    }

    table {
      margin-top: 10%;
      border-collapse: collapse;
      width: 100%;
    }

    th,
    td {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 12px;
    }

    th {
      background-color: #f2f2f2;
    }

    /* Style the "Reply" button */
    .reply-button {
      background-color: #4CAF50;
      color: white;
      padding: 8px 12px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      text-decoration: none;
    }
  </style>
</head>

<body>

  <div id="mySidebar" class="sidebar">
    <a href="{% url 'dash_analytics' %}">Analytics</a>
    <a href="{% url 'approved_events' %}">Approved Events</a>
    <a href="{% url 'all_events' %}">All Events</a>
    <a href="{% url 'rejected_events' %}">Rejected Events</a>
    <a href="{% url 'dash_contact' %}">Contact Forms</a>
  </div>
  <div class="page-content">
    <div class="header">
      <h1>Admin Dashboard</h1>
      <a class="header_button" href="{% url 'logouta_view' %}">Logout</a>
    </div>
    {% block body %}

    {% endblock %}
  </div>
</body>

</html>

eventm/templates/eventm/rejected_events.html
{% extends "eventm/dashboard.html" %}
{% block body %}
  {% if rejected_events %}
    <h1>Rejected Events</h1>
    {% for event in rejected_events %}
      <div style="border: 1px solid #ccc; padding: 10px; margin-bottom: 20px;">
        <p style="font-size: 18px; font-weight: bold;">Name: {{ event.name }}</p>
        <p><strong>Description:</strong> {{ event.description }}</p>
        <p><strong>Location:</strong> {{ event.location }}</p>
        <p><strong>Event Type:</strong> {{ event.event_type }}</p>
      </div>
      <hr>
    {% endfor %}
  {% else %}
    <p>No rejected events available.</p>
  {% endif %}
{% endblock %}

eventm/templates/eventm/signup.html
{% extends "eventm/base1.html" %}
{% block body %}
    <div id="signupContainer">
        <form id="signupForm" method="post" action="{% url 'signup_view' %}">
            {% csrf_token %}
    
            <div class="form-field">
                <label for="id_username">Username:</label>
                <input type="text" name="username" id="id_username" placeholder="Enter your username" required>
            </div>
    
            <div class="form-field">
                <label for="id_email">Email:</label>
                <input type="email" name="email" id="id_email" placeholder="Enter your email" required>
            </div>
    
            <div class="form-field">
                <label for="id_password">Password:</label>
                <input type="password" name="password1" id="id_password" placeholder="Enter your password" required>
            </div>
    
            <div class="form-field">
                <label for="id_confirm_password">Confirm Password:</label>
                <input type="password" name="password2" id="id_confirm_password" placeholder="Confirm your password" required>
            </div>
            
            <!-- Inside the signup form -->
            <div class="form-field">
                <a class="toggle-link" href="{% url 'loginu_view' %}">Already have an account?</a>
            </div>
    
            <button type="submit">Sign Up</button>
        </form>
    </div>         
{% endblock %}